### PR TITLE
TFP Assignment 2

### PR DESCRIPTION
**Pull request by Jeena2001**

### CODE REVIEW

**Comment by nikiljos** [comment]
Please make sure your files and folders are as mentioned in the assignment and update the PR.

Also why your commits are from @Almajoo 🤔

**Comment by Jeena2001** [comment]
Wsl is not working on my laptop.so I used a virtual linux in my frnd's
laptop

**Comment by nikiljos** [comment]
Oh... ok.... Pls do make the file changes

**Comment by nikiljos** [comment]
your first folder should end in _book_app

**Comment by nikiljos** [comment]
Approved👍

**Pull request merged**
