### PR TITLE
added features

### PR DESCRIPTION
**Pull request by Ash-394**

### CODE REVIEW

**Comment by nikiljos** [comment]
Please make sure your files and folders are as mentioned in the assignment and update the PR.

**Comment by Ash-394** [comment]
> Please make sure your files and folders are as mentioned in the assignment and update the PR.
Could you please specify ? I had made the files and folders as per the given assignment.

**Comment by nikiljos** [comment]
image

Your file got some extra text... might have got there when you tried to resolve a merge conflict.... Please remove the extra text

**Comment by Ash-394** [comment]
> 

Resolved the errors.
Thanks!

**Comment by nikiljos** [comment]
Approved👍

**Pull request merged**
