### PR TITLE
Git assignment

### PR DESCRIPTION
**Pull request by UDITHBIJU**
learned to use git

### CODE REVIEW

**Comment by nikiljos** [comment]
Please make sure your files and folders are as mentioned in the assignment and update the PR.

**Comment by UDITHBIJU** [comment]
can't able to find any mistakes in my commit. Could you please explain
what was the mistake?

**Comment by nikiljos** [comment]
2nd file should have 2 sentences as mentioned

**Comment by UDITHBIJU** [comment]
did i need to start it from scratch? or solve it with a single commit

**Comment by nikiljos** [comment]
just solve it with a commit

**Comment by nikiljos** [comment]
Approved👍

**Comment by UDITHBIJU** [comment]
Thank you!

**Comment by UDITHBIJU** [comment]
just did it. could you please check it once again?

**Pull request merged**
