### PR TITLE
Gtech_mulearn_git_assignment

### PR DESCRIPTION
**Pull request by fahadpktn**
Created two branches, develop and feature. Then added file and text to both. Then merged feature to develop branch. There is mistakes happened while merging, but did again and done.

### CODE REVIEW

**Comment by nikiljos** [comment]
Please make sure your files and folders are as mentioned in the assignment and update the PR.

**Comment by nikiljos** [comment]
2nd file should ahve 2 sentences as mentioned

**Comment by fahadpktn** [comment]
> 2nd file should ahve 2 sentences as mentioned

updated

**Comment by nikiljos** [comment]
Approved👍

**Pull request merged**
