### PR TITLE
Book App

### PR DESCRIPTION
**Pull request by Edwinliby**
Assignment -3

### CODE REVIEW

**Comment by nikiljos** [comment]
Please make sure your files and folders are as mentioned in the assignment and update the PR.

**Comment by Edwinliby** [comment]
> Please make sure your files and folders are as mentioned in the assignment and update the PR.
The names are same as mentioned in the assignment, so what is the issue.

**Comment by nikiljos** [comment]
the second file should have 2 sentences

**Comment by Edwinliby** [comment]
> the second file should have 2 sentences

Sorry I missed that part, I have corrected it now.

**Comment by nikiljos** [comment]
As per the assignment, you have to raise PR from your develop branch

**Pull request closed without merging**
