### PR TITLE
git_basics_by_arun

### PR DESCRIPTION
**Pull request by aruncpacp123**
fork the repository
clone the repository
created two branches
created two files and one is updated later
commit changes
merge two branches and pushed it

### CODE REVIEW

**Comment by nikiljos** [comment]
Please make sure your files and folders are as mentioned in the assignment and update the PR.

**Comment by aruncpacp123** [comment]
> Please make sure your files and folders are as mentioned in the assignment and update the PR.

could you tell me what's the problem in it

**Comment by nikiljos** [comment]
image
the first folder name should end in _book_app

**Comment by nikiljos** [comment]
Approved👍

**Pull request merged**
