### PR TITLE
govind feature update

### PR DESCRIPTION
**Pull request by Govind-S-B**

### CODE REVIEW

**Comment by nikiljos** [comment]
Please make sure your files and folders are as mentioned in the assignment and update the PR.

**Comment by Govind-S-B** [comment]
can u point out on what I messed up ?

**Comment by nikiljos** [comment]
Main folder name should have _book_app at end

second file should have 2 sentences as mentioned

**Comment by Govind-S-B** [comment]
@nikiljos done

**Comment by nikiljos** [comment]
Approved👍

**Pull request merged**
