### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Sonaelizebeth**
Learned the basic git commands and added features to the book app 
By Sona Elizebeth Shaji

### CODE REVIEW

**Comment by nikiljos** [comment]
Please make sure your files and folders are as mentioned in the assignment and update the PR.

**Comment by nikiljos** [comment]
Please make sure your files and folders are as mentioned in the assignment and update the PR. Your folder should not be inside bijoy sijo folder

**Comment by Sonaelizebeth** [comment]
hi could you figure me out what is my mistake

**Comment by nikiljos** [comment]
image
the second file needs 2 sentences as per the assignment

**Comment by nikiljos** [comment]
Also your folder should not be inside bijoysijo folder

**Comment by Sonaelizebeth** [comment]
okay but what should i do now

**Comment by Sonaelizebeth** [comment]
should i delete this directory and do it again

**Comment by nikiljos** [comment]
no just make the changes in your local git repo and then ush to the develop branch... no need to close this PR... jsut reopen and push to the same branch

**Comment by Sonaelizebeth** [comment]
okay

**Comment by nikiljos** [comment]
image
second file should have 2 sentences as mentioned

**Comment by Sonaelizebeth** [comment]
okay

**Comment by nikiljos** [comment]
Approved👍

**Pull request merged**
